### ISSUE TITLE
Can't get it to work in Sveltekit

### ISSUE THREAD

**Issue by geoidesic** [sseemayer/svelte-colorpick#4]
Using the basic example from the demo. Copied and pasted into a new route component on Sveltekit.
```
color is not defined

ReferenceError: color is not defined
    at /node_modules/svelte-colorpick/node_modules/d3-color/src/color.js:164:15
    at instantiateModule (/Users/noeldacosta/repo/GitHub/peakVTT/node_modules/vite/dist/node/chunks/dep-cb562f8f.js:68783:166)
```
Here's my package.json
```
...
"dependencies": {
    ...
    "d3-color": "^3.0.1",
    "svelte-colorpick": "^0.1.7"
}
```

**Comment by geoidesic** [comment]
Looks like this was an npm error. Works using yarn instead.
